### ISSUE TITLE
Using script on a local machine

### ISSUE THREAD

**Issue by peterennisrda** [darksidemilk/Create-and-Deploy-Windows-Default-Profiles#4]
I wanted to start with just getting a profile from a local machine. Standalone and not on the domain. Then run tests with local user creation. Stuck on the bench...
Same error if this is run as administrator.
Same error if I put in the domain and share info.
I read the details on fog group but it did not help.
![045capture](https://cloud.githubusercontent.com/assets/1280523/17038250/b5931026-4f49-11e6-855e-0b88f35035cc.PNG)

**Comment by Quazz** [comment]
Windows cannot mount localhost as a network share on itself, that would be crazy. 

You need to direct it to a network share, like the script asks.

**Comment by darksidemilk** [comment]
Copy the script to the root of the c drive and run it from there. The network path missing is the one it copies from I think

On Thu, Jul 21, 2016 at 4:49 PM -0400, "Peter" <notifications@github.com<mailto:notifications@github.com>> wrote:

I wanted to start with just getting a profile from a local machine. Standalone and not on the domain. Then run tests with local user creation. Stuck on the bench...
Same error if this is run as administrator.
Same error if I put in the domain and share info.
I read the details on fog group but it did not help.
[045capture]http://cp.mcafee.com/d/2DRPoO86Qm73hOyOMyqemjtPqdTxRXTsj76QrL3HThjvjdETu7nLtNdUSyyCYyCCe76zAS8KJDDG_45r6dj1fZgg-4ZfVsTIoRc4_R13UjQ_BPq8VZB4QszD-LPzxEVuKVRXBQQTTehpspd7bPfbnhIyyHtdPBgY-F6lK1FJ4SOrKrKr9PCJhbcIvlJ3ycFASO3tfzqI9_2vbVJaveC8FLnvjpN4ttBVd--47PhOOztdMKMWMqeiWafK5TDT_bT8ffeILTpvJrwI30ArxmfH7BwkhBcCSgVsSMYPsSqmQdylF93Rp7Bs4E_I_bX10K7uIvkIn0mk4aCa5MXTtrfCn2QqKOf-xFtd40jFa14QgkJ6iQPh1m1EwQQg7RJFVEwlSNekfd41EE0NwQkCPhOMrf4Ic5eT4Li1M

**Comment by darksidemilk** [comment]
Haven't heard back on this, pretty sure it works if copied locally
